### ISSUE TITLE
Running without docker

### ISSUE THREAD

**Issue by raghavendrajain** [sskorol/vosk-api-gpu#12]
Hi, I am not much familiar with docker would like to build it on my desktop. I am using k80 on GCP's vm instance. Please suggest which file I should follow. thanks a lot!

**Comment by raghavendrajain** [comment]
Tried it, irrespective of what I do, I always get this error
`
make: *** [Makefile:99: batch_recognizer.o] Error 1`

**Comment by sskorol** [comment]
Can you paste more logs? This line is just the result. But it's not descriptive enough to guess what's going on.

**Comment by raghavendrajain** [comment]
I see! Actually, there were no logs created! This error happened during the execution of the following

```
cd /opt/vosk-api/src && \
KALDI_ROOT=/opt/kaldi HAVE_CUDA=1 make -j $(nproc) 
```

**Comment by sskorol** [comment]
Which URL you used for pulling vosk-api?

**Comment by raghavendrajain** [comment]
`git clone -b gpu-fix https://github.com/sskorol/vosk-api.git /opt/vosk-api`

**Comment by sskorol** [comment]
Have you successfully built Kaldi on previous steps?

**Comment by raghavendrajain** [comment]
That's right, it had no errors.

**Comment by sskorol** [comment]
Ok, try pulling from here https://github.com/alphacep/vosk-api.git and run those command again.

**Comment by raghavendrajain** [comment]
Got it, will do right away!

**Comment by raghavendrajain** [comment]
Hey, this does not produce any errors. I followed these 

```
cd /opt/vosk-api/src && \
KALDI_ROOT=/opt/kaldi HAVE_CUDA=1 make -j $(nproc) && \
python3 -m pip install --upgrade pip setuptools wheel cython && \
cd ../python && \
python3 ./setup.py bdist_wheel && \
cd ./dist && pip3 install vosk-*.whl
```

After that, I did the following

```
cd vosk-api/python/example
wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
unzip vosk-model-small-en-us-0.15.zip
mv vosk-model-small-en-us-0.15 model
python3 ./test_simple.py test.wav
```

It gave me the following error though.

```
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.32-py3.7.egg/vosk/__init__.py", line 21, in <module>
    _c = open_dll()
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.32-py3.7.egg/vosk/__init__.py", line 15, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/usr/local/lib/python3.7/dist-packages/vosk-0.3.32-py3.7.egg/vosk/libvosk.so': /usr/local/lib/python3.7/dist-packages/vosk-0.3.32-py3.7.egg/vosk/libvosk.so: undefined symbol: cudaMemcpyAsync
```

**Comment by sskorol** [comment]
What's in your `test_simple.py`?

**Comment by raghavendrajain** [comment]
The `test_simple.py` has the following

```
from vosk import Model, KaldiRecognizer, SetLogLevel
import sys
import os
import wave

SetLogLevel(0)

if not os.path.exists("model"):
    print ("Please download the model from https://alphacephei.com/vosk/models and unpack as 'model' in the current folder.")
    exit (1)

wf = wave.open(sys.argv[1], "rb")
if wf.getnchannels() != 1 or wf.getsampwidth() != 2 or wf.getcomptype() != "NONE":
    print ("Audio file must be WAV format mono PCM.")
    exit (1)

model = Model("model")
rec = KaldiRecognizer(model, wf.getframerate())
rec.SetWords(True)
rec.SetPartialWords(True)

while True:
    data = wf.readframes(4000)
    if len(data) == 0:
        break
    if rec.AcceptWaveform(data):
        print(rec.Result())
    else:
        print(rec.PartialResult())

print(rec.FinalResult())
```
I think this is not suitable so I ran this instead `https://github.com/alphacep/vosk-api/blob/master/python/example/test_gpu_batch.py
`

**Comment by sskorol** [comment]
In general, it's likely Kaldi wasn't correctly built for your platform. It's a crash from a native code. To see native logs you need to run the python process with gdb.

**Comment by raghavendrajain** [comment]
`./test_gpu_batch.py test.wav` seems to be closer to working

It gives the error

```
WARNING ([5.5.1028~1-d8d8]:SelectGpuId():cu-device.cc:243) Not in compute-exclusive mode.  Suggestion: use 'nvidia-smi -c 3' to set compute exclusive mode
LOG ([5.5.1028~1-d8d8]:SelectGpuIdAuto():cu-device.cc:438) Selecting from 1 GPUs
LOG ([5.5.1028~1-d8d8]:SelectGpuIdAuto():cu-device.cc:453) cudaSetDevice(0): Tesla K80  free:4845M, used:6595M, total:11441M, free/total:0.423544
LOG ([5.5.1028~1-d8d8]:SelectGpuIdAuto():cu-device.cc:501) Device: 0, mem_ratio: 0.423544
LOG ([5.5.1028~1-d8d8]:SelectGpuId():cu-device.cc:382) Trying to select device: 0
LOG ([5.5.1028~1-d8d8]:SelectGpuIdAuto():cu-device.cc:511) Success selecting device 0 free mem ratio: 0.423544
LOG ([5.5.1028~1-d8d8]:FinalizeActiveGpu():cu-device.cc:338) The active GPU is [0]: Tesla K80   free:4692M, used:6748M, total:11441M, free/total:0.410172 version 3.7
LOG ([5.5.1028~1-d8d8]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG ([5.5.1028~1-d8d8]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG ([5.5.1028~1-d8d8]:BatchModel():batch_model.cc:52) Loading HCLG from model/graph/HCLG.fst
LOG ([5.5.1028~1-d8d8]:BatchModel():batch_model.cc:56) Loading words from model/graph/words.txt
LOG ([5.5.1028~1-d8d8]:BatchModel():batch_model.cc:64) Loading winfo model/graph/phones/word_boundary.int
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.1028~1-d8d8]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
Traceback (most recent call last):
  File "./test_gpu_batch.py", line 17, in <module>
    fnames = open(sys.argv[1]).readlines()
  File "/opt/conda/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 4: invalid start byte
LOG ([5.5.1028~1-d8d8]:~CachingOptimizingCompiler():nnet-optimize.cc:710) 0.0972 seconds taken in nnet3 compilation total (breakdown: 0.0587 compilation, 0.00505 optimization, 0.0301 shortcut expansion, 0.000912 checking, 0.000153 computing indexes, 0.00224 misc.) + 0 I/O.
```

**Comment by raghavendrajain** [comment]
I see! I think I will just give up here. I have little hope here. I am using tesla k80 on GCP as a platform. Thank you so much for your kind help man.

**Comment by sskorol** [comment]
That's an encoding error while reading cli args in the python code. Should be easy to fix. Note that all those scripts were written just as a set of examples. They can't cover all the environments out of the box and assume you have some programming experience to fix or tune things for your own needs. I'm not a Vosk creator. I'm the same user as you are. Just created a repo to reduce GPU overhead while working with Vosk. But again, setting everything up for the first time requires some engineering skills. So it might be hard for newbies. I see your pain and frustration. But that's how it works.

**Comment by sskorol** [comment]
I guess it's not actual anymore, as you have succeeded with a relative ticket.

**Comment by raghavendrajain** [comment]
@sskorol I could run without docker on the P4 instance. Thanks again for the support.

**Comment by sskorol** [comment]
Great! Have you built it on your own or just reused those new image that I recently pushed?

**Comment by sskorol** [comment]
@raghavendrajain btw, I prepared [instructions](https://github.com/sskorol/vosk-api-gpu#gcp) for building images in GCP. Recent updates contain terraform configs to spawn T4 instance where you can easily deploy Vosk w/ or w/o docker.

**Comment by raghavendrajain** [comment]
> @raghavendrajain btw, I prepared [instructions](https://github.com/sskorol/vosk-api-gpu#gcp) for building images in GCP. Recent updates contain terraform configs to spawn T4 instance where you can easily deploy Vosk w/ or w/o docker.

Oh great, I will check it! I did not see them earlier but just ran the commands you described in `Dockerfile.pc`.

**Comment by sskorol** [comment]
But note that a [build script](https://github.com/sskorol/vosk-api-gpu/blob/main/gcp/build.sh) in gcp folder attempts to patch a model. If you already have a working version, you may want to comment [these lines](https://github.com/sskorol/vosk-api-gpu/blob/main/gcp/build.sh#L29-L45).
