### ISSUE TITLE
install gpu module succesfully but still run on cpu

### ISSUE THREAD

**Issue by v-yunbin** [sskorol/vosk-api-gpu#8]
install gpu module succesfully but still run on cpu

**Comment by sskorol** [comment]
@v-yunbin please provide the details. Your configuration, platform, and code you are running.

**Comment by v-yunbin** [comment]
1. enviroments:
```
   centos7
   cuda11.0
   gcc8.2
   python3.8
```
2. build
```
   cd kaldi/src 
	./configure --mathlib=OPENBLAS_CLAPACK --shared --use-cuda 
	make -j 8 online2 lm rnnlm
   git clone https://github.com/alphacep/vosk-api.git vosk-api
   cd vosk-api/src && \
	KALDI_ROOT=kaldi HAVE_CUDA=1 make -j 8 && 
	python3 ./setup.py bdist_wheel
        pip install dist/vosk*.whl
```
3. run
  ```
  from vosk import GpuInit
    GpuInit()
```

**Comment by sskorol** [comment]
- What's your hardware?
- What Kaldi repo/branch/configuration has been used for Kaldi?
- Why did you remove `sed` replacements from the script?
- Are you using docker or running code on the host's OS?

**Comment by v-yunbin** [comment]
> * What's your hardware?
16 core cpu 128g mem
> * What Kaldi repo/branch/configuration has been used?
kaldi-lookahead
> * Why did you remove `sed` replacements from the script?
i dont know ，i build cpu version like this and cpu version is normal
> * Are you using docker or running code on the host's OS?
not use docker

**Comment by sskorol** [comment]
Where did you find a `kaldi-lookahead` branch in this [repo](https://github.com/alphacep/kaldi/branches)? Vosk uses its own custom Kaldi fork.

Please follow instructions from this [Dockerfile](https://github.com/sskorol/vosk-api-gpu/blob/main/Dockerfile.pc). It'll give you the correct Kaldi / Vosk configuration.

**Comment by v-yunbin** [comment]
I follow  your instructions dockerfile， when make openfst， get follow error：
```
configure: error: in `/home/.open_source/docker/kaldi-gpu/tools/openfst-1.8.0':
configure: error: Test float equality failed! Compile with -msse -mfpmath=sse if using g++.
See `config.log' for more details
make: *** [openfst-1.8.0/Makefile] Error 1
```

**Comment by fmbao** [comment]
same question
